# Site settings
title: RayChou Blog
logoTitle: 吾日三省吾身
SEOTitle: RayChou blog | 技术博客
header-img: img/home-bg.jpeg
email: 1174786922@qq.com
description: "python, Vue, jmeter , java, tester"
keyword: "python, Vue, jmeter , java, tester"
url: ""              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
wechat_username:     ZL13163331097
zhihu_username:     jia-wei-27
github_username:    JYH89


# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Analytics settings
# Baidu Analytics
ba_track_id: b959664f3349ddb0e15b20bd38897dd6
# Google Analytics



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "告别结果焦虑，慢下来去工作生活,遇见更好的自己。"
sidebar-avatar: /img/me.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "音乐",
        href: "https://music.163.com/#/user/home?id=318807382"
    },{
        title: "FCC主页",
        href: "https://www.freecodecamp.cn/jyh89"
    },{
       title: "leetcode主页",
       href: "https://leetcode-cn.com/u/jyh89"
    },{
      title: "查看更多请关注我的微信公共号。",
      href: "https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzAwOTQ2ODc3OQ==&scene=124#wechat_redirect"
    }
]

theme: jekyll-theme-cayman
